### Check 10-Year Historical Return for Aggressive Portfolio

In [8]:
import pandas as pd
from datetime import datetime, timedelta
import yahoo_fin.stock_info as si

# Define the assets and the period
asset_list = ["NVDA", "TSLA", "AMZN", "META", "ADBE", "CRM", "AVGO", "LLY", "^TNX", "WELL"]
end_date = datetime.now()
start_date = end_date - timedelta(days=10*365)  # Approx 10 years

# Prepare an empty DataFrame to concatenate all asset DataFrames
all_assets_df = pd.DataFrame()

# Fetch and concatenate data for each asset
for asset in asset_list:
    print(f"Fetching data for {asset}...")
    df = si.get_data(asset, start_date=start_date, end_date=end_date, index_as_date=True)
    df.columns = pd.MultiIndex.from_product([[asset], df.columns])  # Multi-level indexing
    all_assets_df = pd.concat([all_assets_df, df], axis=1) if not all_assets_df.empty else df

# Drop any rows with missing data to ensure consistency
all_assets_df.dropna(inplace=True)

# Function to calculate historical annual returns
def calculate_annual_returns(data, years):
    annual_returns = {}
    for asset in asset_list:
        initial_value = data[asset, 'close'].iloc[0]
        final_value = data[asset, 'close'].iloc[-1]
        cagr = (final_value / initial_value) ** (1 / years) - 1
        annual_returns[asset] = cagr * 100  # Convert to percentage
    return annual_returns

# Calculate the historical annual returns
years = (end_date - start_date).days / 365.25
historical_annual_returns = calculate_annual_returns(all_assets_df, years)

# Print the historical annual returns for each asset
print("Historical Annual Returns (%):")
for asset, returns in historical_annual_returns.items():
    print(f"{asset}: {returns:.2f}%")

Fetching data for NVDA...
Fetching data for TSLA...
Fetching data for AMZN...
Fetching data for META...
Fetching data for ADBE...
Fetching data for CRM...
Fetching data for AVGO...
Fetching data for LLY...
Fetching data for ^TNX...
Fetching data for WELL...
Historical Annual Returns (%):
NVDA: 69.23%
TSLA: 31.32%
AMZN: 29.18%
META: 23.07%
ADBE: 23.48%
CRM: 18.51%
AVGO: 34.13%
LLY: 28.60%
^TNX: 5.63%
WELL: 4.07%

### Check 10-Year Historical Return for Moderate Portfolio

In [9]:
import pandas as pd
from datetime import datetime, timedelta
import yahoo_fin.stock_info as si

# Define the assets and the period
asset_list = ["AAPL", "MSFT", "V", "UNH", "COST", "MA", "HD", "JPM", "^TNX","O"]
end_date = datetime.now()
start_date = end_date - timedelta(days=10*365)  # Approx 10 years

# Prepare an empty DataFrame to concatenate all asset DataFrames
all_assets_df = pd.DataFrame()

# Fetch and concatenate data for each asset
for asset in asset_list:
    print(f"Fetching data for {asset}...")
    df = si.get_data(asset, start_date=start_date, end_date=end_date, index_as_date=True)
    df.columns = pd.MultiIndex.from_product([[asset], df.columns])  # Multi-level indexing
    all_assets_df = pd.concat([all_assets_df, df], axis=1) if not all_assets_df.empty else df

# Drop any rows with missing data to ensure consistency
all_assets_df.dropna(inplace=True)

# Function to calculate historical annual returns
def calculate_annual_returns(data, years):
    annual_returns = {}
    for asset in asset_list:
        initial_value = data[asset, 'close'].iloc[0]
        final_value = data[asset, 'close'].iloc[-1]
        cagr = (final_value / initial_value) ** (1 / years) - 1
        annual_returns[asset] = cagr * 100  # Convert to percentage
    return annual_returns

# Calculate the historical annual returns
years = (end_date - start_date).days / 365.25
historical_annual_returns = calculate_annual_returns(all_assets_df, years)

# Print the historical annual returns for each asset
print("Historical Annual Returns (%):")
for asset, returns in historical_annual_returns.items():
    print(f"{asset}: {returns:.2f}%")

Fetching data for AAPL...
Fetching data for MSFT...
Fetching data for V...
Fetching data for UNH...
Fetching data for COST...
Fetching data for MA...
Fetching data for HD...
Fetching data for JPM...
Fetching data for ^TNX...
Fetching data for O...
Historical Annual Returns (%):
AAPL: 24.22%
MSFT: 26.23%
V: 17.69%
UNH: 20.42%
COST: 20.57%
MA: 19.59%
HD: 16.11%
JPM: 13.37%
^TNX: 5.63%
O: 2.63%

### Check 10-Year Historical Return for Low Portfolio

In [10]:
import pandas as pd
from datetime import datetime, timedelta
import yahoo_fin.stock_info as si

# Define the assets and the period
asset_list = ["JNJ", "PG", "BRK-B", "MRK", "CVX", "XOM", "ABBV", "^TYX", "CCI"]
end_date = datetime.now()
start_date = end_date - timedelta(days=10*365)  # Approx 10 years

# Prepare an empty DataFrame to concatenate all asset DataFrames
all_assets_df = pd.DataFrame()

# Fetch and concatenate data for each asset
for asset in asset_list:
    print(f"Fetching data for {asset}...")
    df = si.get_data(asset, start_date=start_date, end_date=end_date, index_as_date=True)
    df.columns = pd.MultiIndex.from_product([[asset], df.columns])  # Multi-level indexing
    all_assets_df = pd.concat([all_assets_df, df], axis=1) if not all_assets_df.empty else df

# Drop any rows with missing data to ensure consistency
all_assets_df.dropna(inplace=True)

# Function to calculate historical annual returns
def calculate_annual_returns(data, years):
    annual_returns = {}
    for asset in asset_list:
        initial_value = data[asset, 'close'].iloc[0]
        final_value = data[asset, 'close'].iloc[-1]
        cagr = (final_value / initial_value) ** (1 / years) - 1
        annual_returns[asset] = cagr * 100  # Convert to percentage
    return annual_returns

# Calculate the historical annual returns
years = (end_date - start_date).days / 365.25
historical_annual_returns = calculate_annual_returns(all_assets_df, years)

# Print the historical annual returns for each asset
print("Historical Annual Returns (%):")
for asset, returns in historical_annual_returns.items():
    print(f"{asset}: {returns:.2f}%")

Fetching data for JNJ...
Fetching data for PG...
Fetching data for BRK-B...
Fetching data for MRK...
Fetching data for CVX...
Fetching data for XOM...
Fetching data for ABBV...
Fetching data for ^TYX...
Fetching data for CCI...
Historical Annual Returns (%):
JNJ: 4.04%
PG: 7.19%
BRK-B: 12.22%
MRK: 9.32%
CVX: 2.51%
XOM: 1.26%
ABBV: 12.13%
^TYX: 3.16%
CCI: 2.35%

In [1]:
import os
import numpy as np
import pandas as pd
import yahoo_fin.stock_info as si
from datetime import datetime, timedelta
from MCPortfolioSimulator_LR import PortfolioSimulator

# Prepare an empty DataFrame to concatenate all asset DataFrames
all_assets_df = pd.DataFrame()

# List of assets to fetch data for
asset_list = ["NVDA", "TSLA", "AMZN", "META", "ADBE", "CRM", "AVGO", "LLY", "^TNX", "WELL"]  # High Risk
#asset_list = ["AAPL", "MSFT", "V", "UNH", "COST", "MA", "HD", "JPM", "^TNX","O"] #Moderate Risk
#asset_list = ["JNJ", "PG", "BRK-B", "MRK", "CVX", "XOM", "ABBV", "^TYX", "CCI"] #Low Risk
# Define the start and end dates for fetching the data
end_date = datetime.now()
start_date = end_date - timedelta(days=10*365)  # Approximately 10 years

# Fetch and concatenate data for each asset
for asset in asset_list:
    print(f"Fetching data for {asset}...")
    df = si.get_data(asset, start_date=start_date, end_date=end_date, index_as_date=True)
    
    # Standardize column names
    df.rename(columns={
        'open': 'open', 'high': 'high', 'low': 'low', 'close': 'close',
        'adjclose': 'adj close', 'volume': 'volume'
    }, inplace=True)
    
    # Adjust DataFrame column names for multi-level indexing
    if all_assets_df.empty:
        all_assets_df = df
        all_assets_df.columns = pd.MultiIndex.from_product([[asset], all_assets_df.columns])
    else:
        df.columns = pd.MultiIndex.from_product([[asset], df.columns])
        all_assets_df = pd.concat([all_assets_df, df], axis=1)

# Drop any rows with missing data to ensure consistency
all_assets_df.dropna(inplace=True)

# Display the first few rows of the consolidated data
display(all_assets_df)

# Monte Carlo simulation configuration
weights = [.10, .10, .10, .10, .10, .10, .10, .10, .15, .05]  #High Risk
#weights = [.10, .10, .10, .10, .10, .10, .10, .10, .15, .05] #Moderate Risk
#weights = [.12, .12, .12, .11, .11, .11, .11, .15, .05]  #Low Risk

historical_returns_high_risk = {
    "NVDA": 69.23, "TSLA": 31.32, "AMZN": 29.18, "META": 23.07, "ADBE": 23.48,
    "CRM": 18.51, "AVGO": 34.13, "LLY": 28.60, "^TNX": 5.63, "WELL": 4.07
}

historical_returns_moderate_risk = {
    "AAPL": 24.22,
    "MSFT": 26.23,
    "V": 17.69,
    "UNH": 20.42,
    "COST": 20.57,
    "MA": 19.59,
    "HD": 16.11,
    "JPM": 13.37,
    "^TNX": 5.63,
    "O": 2.63
}

historical_returns_low_risk = {
    "JNJ": 4.04,
    "PG": 7.19,
    "BRK-B": 12.22,
    "MRK": 9.32,
    "CVX": 2.51,
    "XOM": 1.26,
    "ABBV": 12.13,
    "^TYX": 3.16,
    "CCI": 2.35
}

# Initialize the PortfolioSimulator
sim_returns2 = PortfolioSimulator(
    portfolio_data=all_assets_df,
    annual_returns=historical_returns_high_risk,
    weights=weights,
    num_simulation=500,
    num_trading_days=252*30,
    
)

# # Display the first few rows of the portfolio data
display(sim_returns2.portfolio_data)
display(sim_returns2.daily_log_returns)

c:\Users\kahbe\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

Fetching data for NVDA...
Fetching data for TSLA...
Fetching data for AMZN...
Fetching data for META...
Fetching data for ADBE...
Fetching data for CRM...
Fetching data for AVGO...
Fetching data for LLY...
Fetching data for ^TNX...
Fetching data for WELL...

                  NVDA                                                  \
                  open        high         low       close   adj close
2014-05-09    4.485000    4.527500    4.427500    4.512500    4.276275
2014-05-12    4.522500    4.655000    4.520000    4.645000    4.401839
2014-05-13    4.582500    4.657500    4.555000    4.570000    4.330765
2014-05-14    4.572500    4.590000    4.522500    4.525000    4.288123
2014-05-15    4.515000    4.540000    4.455000    4.500000    4.264430
...                ...         ...         ...         ...         ...
2024-04-29  875.950012  879.919983  852.659973  877.570007  877.570007
2024-04-30  872.400024  888.190002  863.000000  864.020020  864.020020
2024-05-01  850.770020  860.000000  812.549988  830.409973  830.409973
2024-05-02  844.489990  862.369995  832.000000  858.169983  858.169983
2024-05-03  877.890015  892.809998  870.400085  887.830017  887.830017

                                     TSLA                          ...  \
                volume ticker        open        high         low  ...
2014-05-09  53953200.0   NVDA   11.990667   12.226667   11.814667  ...
2014-05-12  29985600.0   NVDA   12.258000   12.479333   11.992000  ...
2014-05-13  22110400.0   NVDA   12.250667   12.756000   12.200000  ...
2014-05-14  21432000.0   NVDA   12.596667   12.898667   12.473333  ...
2014-05-15  32589600.0   NVDA   12.665333   12.844000   12.353333  ...
...                ...    ...         ...         ...         ...  ...
2024-04-29  38897100.0   NVDA  188.419998  198.869995  184.539993  ...
2024-04-30  36370900.0   NVDA  186.979996  190.949997  182.839996  ...
2024-05-01  55986300.0   NVDA  182.000000  185.860001  179.009995  ...
2024-05-02  37789800.0   NVDA  182.860001  184.600006  176.020004  ...
2024-05-03  39834072.0   NVDA  182.009995  184.779999  178.429993  ...

                ^TNX                     WELL                        \
           adj close volume ticker       open       high        low
2014-05-09     2.623    0.0   ^TNX  64.220001  65.099998  64.099998
2014-05-12     2.656    0.0   ^TNX  64.370003  64.419998  63.750000
2014-05-13     2.618    0.0   ^TNX  64.250000  64.839996  63.720001
2014-05-14     2.543    0.0   ^TNX  64.089996  64.500000  63.770000
2014-05-15     2.502    0.0   ^TNX  63.950001  64.599998  63.869999
...              ...    ...    ...        ...        ...        ...
2024-04-29     4.614    0.0   ^TNX  95.089996  95.830002  94.620003
2024-04-30     4.686    0.0   ^TNX  94.519997  98.190002  94.519997
2024-05-01     4.595    0.0   ^TNX  95.019997  96.050003  94.139999
2024-05-02     4.571    0.0   ^TNX  95.000000  96.190002  93.720001
2024-05-03     4.500    0.0   ^TNX  96.959999  97.205002  94.660004


                close  adj close     volume ticker
2014-05-09  64.389999  42.408825  2097200.0   WELL
2014-05-12  64.309998  42.356144  1719500.0   WELL
2014-05-13  64.000000  42.151958  1405100.0   WELL
2014-05-14  63.970001  42.132198  1892500.0   WELL
2014-05-15  64.550003  42.514210  1961500.0   WELL
...               ...        ...        ...    ...
2024-04-29  95.779999  95.779999  2607900.0   WELL
2024-04-30  95.279999  95.279999  3879100.0   WELL
2024-05-01  94.360001  94.360001  2283500.0   WELL
2024-05-02  96.080002  96.080002  3129100.0   WELL
2024-05-03  95.809998  95.809998  2557328.0   WELL

[2513 rows x 70 columns]

                  NVDA                                                  \
                  open        high         low       close   adj close
2014-05-09    4.485000    4.527500    4.427500    4.512500    4.276275
2014-05-12    4.522500    4.655000    4.520000    4.645000    4.401839
2014-05-13    4.582500    4.657500    4.555000    4.570000    4.330765
2014-05-14    4.572500    4.590000    4.522500    4.525000    4.288123
2014-05-15    4.515000    4.540000    4.455000    4.500000    4.264430
...                ...         ...         ...         ...         ...
2024-04-29  875.950012  879.919983  852.659973  877.570007  877.570007
2024-04-30  872.400024  888.190002  863.000000  864.020020  864.020020
2024-05-01  850.770020  860.000000  812.549988  830.409973  830.409973
2024-05-02  844.489990  862.369995  832.000000  858.169983  858.169983
2024-05-03  877.890015  892.809998  870.400085  887.830017  887.830017

                                                TSLA              ...   ^TNX  \
                volume ticker log_return        open        high  ... ticker
2014-05-09  53953200.0   NVDA        NaN   11.990667   12.226667  ...   ^TNX
2014-05-12  29985600.0   NVDA   0.028940   12.258000   12.479333  ...   ^TNX
2014-05-13  22110400.0   NVDA  -0.016278   12.250667   12.756000  ...   ^TNX
2014-05-14  21432000.0   NVDA  -0.009896   12.596667   12.898667  ...   ^TNX
2014-05-15  32589600.0   NVDA  -0.005540   12.665333   12.844000  ...   ^TNX
...                ...    ...        ...         ...         ...  ...    ...
2024-04-29  38897100.0   NVDA   0.000251  188.419998  198.869995  ...   ^TNX
2024-04-30  36370900.0   NVDA  -0.015561  186.979996  190.949997  ...   ^TNX
2024-05-01  55986300.0   NVDA  -0.039676  182.000000  185.860001  ...   ^TNX
2024-05-02  37789800.0   NVDA   0.032883  182.860001  184.600006  ...   ^TNX
2024-05-03  39834072.0   NVDA   0.033978  182.009995  184.779999  ...   ^TNX

                            WELL                                              \
           log_return       open       high        low      close  adj close
2014-05-09        NaN  64.220001  65.099998  64.099998  64.389999  42.408825
2014-05-12   0.012503  64.370003  64.419998  63.750000  64.309998  42.356144
2014-05-13  -0.014411  64.250000  64.839996  63.720001  64.000000  42.151958
2014-05-14  -0.029066  64.089996  64.500000  63.770000  63.970001  42.132198
2014-05-15  -0.016254  63.950001  64.599998  63.869999  64.550003  42.514210
...               ...        ...        ...        ...        ...        ...
2024-04-29  -0.011850  95.089996  95.830002  94.620003  95.779999  95.779999
2024-04-30   0.015484  94.519997  98.190002  94.519997  95.279999  95.279999
2024-05-01  -0.019611  95.019997  96.050003  94.139999  94.360001  94.360001
2024-05-02  -0.005237  95.000000  96.190002  93.720001  96.080002  96.080002
2024-05-03  -0.015655  96.959999  97.205002  94.660004  95.809998  95.809998


               volume ticker log_return
2014-05-09  2097200.0   WELL        NaN
2014-05-12  1719500.0   WELL  -0.001243
2014-05-13  1405100.0   WELL  -0.004832
2014-05-14  1892500.0   WELL  -0.000469
2014-05-15  1961500.0   WELL   0.009026
...               ...    ...        ...
2024-04-29  2607900.0   WELL   0.015149
2024-04-30  3879100.0   WELL  -0.005234
2024-05-01  2283500.0   WELL  -0.009703
2024-05-02  3129100.0   WELL   0.018064
2024-05-03  2557328.0   WELL  -0.002814

[2513 rows x 80 columns]

array([0.00208765, 0.00108122, 0.00101602, 0.00082374, 0.00083694,
       0.00067392, 0.00116524, 0.00099816, 0.00021735, 0.00015831])

In [2]:
display(sim_returns2.calc_cumulative_return())

Running Monte Carlo simulation number 0.
Running Monte Carlo simulation number 10.
Running Monte Carlo simulation number 20.
Running Monte Carlo simulation number 30.
Running Monte Carlo simulation number 40.
Running Monte Carlo simulation number 50.
Running Monte Carlo simulation number 60.
Running Monte Carlo simulation number 70.
Running Monte Carlo simulation number 80.
Running Monte Carlo simulation number 90.
Running Monte Carlo simulation number 100.
Running Monte Carlo simulation number 110.
Running Monte Carlo simulation number 120.
Running Monte Carlo simulation number 130.
Running Monte Carlo simulation number 140.
Running Monte Carlo simulation number 150.
Running Monte Carlo simulation number 160.
Running Monte Carlo simulation number 170.
Running Monte Carlo simulation number 180.
Running Monte Carlo simulation number 190.
Running Monte Carlo simulation number 200.
Running Monte Carlo simulation number 210.
Running Monte Carlo simulation number 220.
Running Monte Carlo simulation number 230.
Running Monte Carlo simulation number 240.
Running Monte Carlo simulation number 250.
Running Monte Carlo simulation number 260.
Running Monte Carlo simulation number 270.
Running Monte Carlo simulation number 280.
Running Monte Carlo simulation number 290.
Running Monte Carlo simulation number 300.
Running Monte Carlo simulation number 310.
Running Monte Carlo simulation number 320.
Running Monte Carlo simulation number 330.
Running Monte Carlo simulation number 340.
Running Monte Carlo simulation number 350.
Running Monte Carlo simulation number 360.
Running Monte Carlo simulation number 370.
Running Monte Carlo simulation number 380.
Running Monte Carlo simulation number 390.
Running Monte Carlo simulation number 400.
Running Monte Carlo simulation number 410.
Running Monte Carlo simulation number 420.
Running Monte Carlo simulation number 430.
Running Monte Carlo simulation number 440.
Running Monte Carlo simulation number 450.
Running Monte Carlo simulation number 460.
Running Monte Carlo simulation number 470.
Running Monte Carlo simulation number 480.
Running Monte Carlo simulation number 490.

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,1.008642,1.010658,0.997292,1.011436,1.016140,1.000553,1.010078,1.005297,1.006311,0.992140,...,1.008250,1.016381,1.001208,0.993140,0.992044,1.001265,1.004483,0.995026,1.008827,1.001317
2,1.002038,1.010776,0.998665,1.005551,1.001778,0.997367,0.997492,1.006135,0.996212,0.996247,...,1.021156,1.016534,1.002974,0.992396,0.996654,1.001129,1.000254,0.992886,1.007525,1.006517
3,1.000324,1.003902,1.004584,1.008517,0.996306,0.999986,0.993102,1.008079,1.013559,0.991069,...,1.018862,1.015923,1.006677,0.996825,1.000346,1.000595,0.992734,1.004202,1.014045,1.008671
4,1.001707,1.005373,1.011382,0.997394,0.989008,0.994444,1.004123,1.004601,1.017724,0.986404,...,1.014094,1.023520,1.004712,0.996483,0.992337,0.999981,0.998577,1.000447,1.024455,1.000500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7556,6245.928462,7124.492338,2819.454044,12018.760240,4833.171364,2746.267608,7835.551110,3242.980968,5316.850902,1872.597270,...,7871.207270,2888.221054,2527.381864,3231.449317,3460.596637,5172.570661,5321.741952,2971.834910,3072.431097,2175.555050
7557,6270.440712,7110.862874,2834.949905,11840.545615,4827.270915,2777.803637,7879.254846,3231.231291,5352.607324,1874.895983,...,7873.876106,2877.530535,2519.403958,3230.832885,3464.619827,5160.433551,5391.569820,2984.860280,3086.268791,2154.550828
7558,6308.226041,7241.044431,2849.197881,11684.097647,4873.954871,2803.635360,7868.607022,3252.223056,5307.987555,1873.090905,...,7804.200142,2894.281531,2534.058653,3251.150670,3472.824579,5145.479567,5394.020986,2952.583236,3059.532041,2159.854742
7559,6265.005923,7259.615886,2850.818819,11706.814669,4926.813221,2777.618601,7922.777833,3219.949100,5326.781180,1870.292296,...,7783.477733,2915.304624,2567.063995,3263.407369,3471.352420,5146.336004,5427.017288,2977.790038,3019.022410,2145.964252
7560,6217.215626,7233.786492,2858.591759,11573.487029,4920.789006,2790.084062,7982.125901,3241.901052,5344.481220,1886.906523,...,7690.378949,2958.358360,2565.679150,3293.531860,3487.276827,5159.102383,5460.721910,2991.293776,3079.275997,2172.837123

In [3]:
# Fetch summary statistics from the Monte Carlo simulation results
all_stats2 = sim_returns2.summarize_cumulative_return()

print(all_stats2)

count             500.000000
mean             5823.844058
std              3634.386207
min               716.189427
25%              3172.276640
50%              5135.020119
75%              7505.372080
max             28930.055643
95% CI Lower     1408.994043
95% CI Upper    14783.684303
Name: 7560, dtype: float64

c:\Users\kahbe\Documents\GitHub\Investment-Chatbot\Monte Carlo Simulation\MCPortfolioSimulator_LR.py:114: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  return metrics.append(ci_series)

In [4]:
# Set initial investment
initial_investment = 20000

# Use the lower and upper `95%` confidence intervals to calculate the range of the possible outcomes of our $20,000
port_high_return = round(initial_investment * all_stats2[9],2) 
port_low_return = round(initial_investment * all_stats2[8],2)

# Print results
print(f"There is a 95% chance that an initial investment of ${initial_investment} in the portfolio"
      f" over the next 30 years will end within in the range of"
      f" ${port_low_return} and ${port_high_return}")

There is a 95% chance that an initial investment of $20000 in the portfolio over the next 30 years will end within in the range of $28179880.85 and $295673686.07

In [5]:
initial_investment = 20000
lower_estimate = 28179880.85 
upper_estimate = 295673686.07

years = 30

lower_annual_return = (lower_estimate / initial_investment) ** (1 / years) - 1
upper_annual_return = (upper_estimate / initial_investment) ** (1 / years) - 1

print(f"Lower Implied Annual Return: {lower_annual_return * 100:.2f}%")
print(f"Upper Implied Annual Return: {upper_annual_return * 100:.2f}%")

Lower Implied Annual Return: 27.34%
Upper Implied Annual Return: 37.72%